-- GENERATED by tools/port_items.py - do not hand-edit.
-- item type id -> { eocs, consume, need_wielding } for the
-- MOM_EOC_ITEM Lua iuse (mom_hooks.iuse_eoc_item).
return {
  ['abjuration_stone'] = { eocs = { 'EOC_MOM_ABJURATION_STONE_EFFECTS' }, consume = true, need_wielding = false },
  ['cards_zener'] = { eocs = { 'EOC_ZENER_DECK' }, consume = false, need_wielding = false },
  ['cascade_stone'] = { eocs = { 'EOC_MOM_CASCADE_STONE_EFFECTS' }, consume = true, need_wielding = false },
  ['chaos_stone'] = { eocs = { 'EOC_CAUSE_PORTAL_STORM' }, consume = true, need_wielding = false },
  ['force_field_generator'] = { eocs = { 'EOC_FORCE_FIELD_GENERATOR_ACTIVATION' }, consume = false, need_wielding = false },
  ['matrix_crystal_biokinesis'] = { eocs = { 'EOC_BIOKIN_MATRIX_AWAKENING' }, consume = true, need_wielding = true },
  ['matrix_crystal_clairsentience'] = { eocs = { 'EOC_CLAIR_MATRIX_AWAKENING' }, consume = true, need_wielding = true },
  ['matrix_crystal_coruscating'] = { eocs = { 'EOC_CORUSCATING_MATRIX' }, consume = true, need_wielding = false },
  ['matrix_crystal_drained'] = { eocs = { 'EOC_DRAINED_MATRIX' }, consume = true, need_wielding = false },
  ['matrix_crystal_electrokinesis'] = { eocs = { 'EOC_ELECTRO_MATRIX_AWAKENING' }, consume = true, need_wielding = true },
  ['matrix_crystal_photokinesis'] = { eocs = { 'EOC_PHOTOKIN_MATRIX_AWAKENING' }, consume = true, need_wielding = true },
  ['matrix_crystal_pyrokinesis'] = { eocs = { 'EOC_PYROKIN_MATRIX_AWAKENING' }, consume = true, need_wielding = true },
  ['matrix_crystal_telekinesis'] = { eocs = { 'EOC_TELEKIN_MATRIX_AWAKENING' }, consume = true, need_wielding = true },
  ['matrix_crystal_telepathy'] = { eocs = { 'EOC_TEEP_MATRIX_AWAKENING' }, consume = true, need_wielding = true },
  ['matrix_crystal_teleportation'] = { eocs = { 'EOC_TELEPORT_MATRIX_AWAKENING' }, consume = true, need_wielding = true },
  ['psi_usb_rad_recipes'] = { eocs = { 'EOC_PSI_USB_RAD_RECIPE' }, consume = false, need_wielding = false },
  ['psionic_transporter_remote_on'] = { eocs = { 'EOC_PSI_TRANSPORTER_REMOTE_TELEPORT' }, consume = false, need_wielding = false },
  ['quest_starter_note_fifth_sun_cuachic'] = { eocs = { 'EOC_QUEST_STARTER_NOTE_FIFTH_SUN_CUACHIC' }, consume = false, need_wielding = false },
  ['translation_stone'] = { eocs = { 'EOC_NETHER_EFFECT_APPLY_TELEPORT_MISJUMP' }, consume = true, need_wielding = false },
}
