-- GENERATED by tools/port_monsters.py — do not hand-edit.
-- Monster death-effect bridge data: mon id -> { spell?, level?,
-- eoc?, message? }.  mom_hooks.on_mon_death dispatches it (BN's
-- death_function can't cast a spell / run an EOC / print a custom
-- message; DDA's death_function object could).
return {
  ["mon_feral_human_photokin"] = { spell = "death_blind_oneineight" },
  ["mon_feral_human_photokin2"] = { spell = "death_blind_oneinfour" },
  ["mon_feral_human_photokin3"] = { spell = "death_blindness", message = "%1$s shrieks and unleashes a powerful blinding flash!" },
  ["mon_feral_human_porter3"] = { spell = "teleport_summon_monster", message = "As the %1$s dies, the air warps around them!" },
  ["mon_feral_human_pyrokin"] = { spell = "death_explosion_oneineight" },
  ["mon_feral_human_pyrokin2"] = { spell = "death_explosion_oneinfour" },
  ["mon_feral_human_pyrokin3"] = { spell = "death_conflagration", message = "%1$s screams and the flames around them burst outward!" },
  ["mon_feral_human_teep"] = { spell = "death_psychic_scream", level = 5, message = "As the %1$s dies, a scream fills your mind!" },
  ["mon_feral_human_teep2"] = { spell = "death_psychic_scream", level = 10, message = "As the %1$s dies, a scream fills your mind!" },
  ["mon_feral_human_teep3"] = { spell = "death_psychic_scream", level = 15, message = "As the %1$s dies, a scream fills your mind!" },
  ["mon_feral_human_telekin"] = { spell = "death_telekeinetic_hit_oneinfive", message = "As the %1$s dies, a wave of force explodes outward!" },
  ["mon_feral_human_telekin2"] = { spell = "death_telekeinetic_hit_oneinthree", message = "As the %1$s dies, a wave of force explodes outward!" },
  ["mon_feral_human_telekin3"] = { spell = "death_telekeinetic_hit_oneinthree", message = "As the %1$s dies, a wave of force explodes outward!" },
  ["mon_feral_human_vita3"] = { eoc = "EOC_VITAKIN3_DEATH_EFFECT", message = "As the %s succumbs to their wounds, they suddenly rise up with new vigor!" },
  ["mon_nether_eater"] = { message = "The %s melts away." },
  ["mon_nether_silent_one_passive"] = { message = "The %s melts away." },
  ["mon_photokin_army_image"] = { spell = "photokinetic_light_explosion_monster", level = 5, message = "The %s explodes in a brilliant burst of light!" },
  ["mon_photokin_image"] = { message = "The %s disappears." },
  ["mon_pyrokin_hotair_1"] = { message = "The %s disappears." },
  ["mon_zombie_blank"] = { spell = "delete_nullifying_fields_monster" },
  ["mon_zombie_nullpsi"] = { spell = "delete_nullifying_fields_monster" },
  ["mon_zombie_psi_void"] = { spell = "delete_nullifying_fields_monster" },
}
